"""init

Revision ID: 3347940f716c
Revises: 
Create Date: 2025-06-02 09:02:21.767785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3347940f716c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('api_id', sa.BigInteger(), nullable=False),
    sa.Column('api_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('entities',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'id')
    )
    op.create_table('sent_files',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('md5_digest', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('hash', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'md5_digest', 'file_size', 'type')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('server_address', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('auth_key', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'dc_id')
    )
    op.create_table('update_state',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('pts', sa.BigInteger(), nullable=True),
    sa.Column('qts', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.BigInteger(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'entity_id')
    )
    op.create_table('version',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    op.drop_table('update_state')
    op.drop_table('sessions')
    op.drop_table('sent_files')
    op.drop_table('entities')
    op.drop_table('accounts')
    # ### end Alembic commands ###
